---

services:

  web-app:
    image: nginx
    container_name: nginx
    depends_on:
      - php
    restart: unless-stopped
    volumes:
      - /srv/web:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-app.entrypoints=web-secure"
      - "traefik.http.routers.web-app.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.web-app.tls=true"
      - "traefik.http.routers.web-app.tls.certresolver=default"
      - "traefik.http.routers.web-app.middlewares=security-headers"
      - "traefik.http.services.web-app.loadbalancer.server.port=80"

    networks:
      - traefik_proxy

  php:
    image: php:fpm
    container_name: php
    user: "33:33"
    networks:
      - traefik_proxy

    volumes:
      - /srv/web:/usr/share/nginx/html

networks:
  traefik_proxy:
    external: true
